# This is the default format. 
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "LICENSE"]
highlighter: pygments
github: [Repository metadata]
markdown: redcarpet

version: v1.1.0

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : ...computing works.
tagline: computing works, life is "random".
author :
  name : Adriano Ribeiro
  github : drr00t
  twitter : drr00t

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
url : http://drr00t.github.io

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: https://github.com/drr00t/
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: drr00t
  
