title: Data Streaming Architectures Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of architectures for data streaming and real-time analytics, showcasing solutions, 
  projects, and hands-on experience in stream data processing, system integration, and real-time data analysis.
permalink: ":title/"
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: drr00t #if your site has a twitter account, enter it here

# Author Settings
author: Adriano dos Santos Ribeiro # add your name
author-img: eu-tdc.jpg # add your photo
about-author: Open Source developer, passionate about data streaming architecture and technologies.
social-twitter: drr00t # add your Twitter handle
social-github: drr00t # add your Github handle
social-linkedin: drr00t # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: disqus_D2lkOSUgk0 # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
